import Head from "next/head";
import NavBar from "../../components/layout/NavBar";

export default function Blog() {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
    </div>
  );
}
