import Head from "next/head";
import MainLayout from "../../components/layout/MainLayout";

export default function Blog() {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <p>blog page</p>
      </MainLayout>
    </div>
  );
}
