import Head from "next/head";
import MainLayout from "../components/layout/MainLayout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <p>main page</p>
      </MainLayout>
    </div>
  );
}
