import Head from "next/head";
import MainLayout from "../components/layout/MainLayout";
import SideBar from "../components/layout/SideBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="w-full flex flex-col-reverse lg:flex-row">
          <SideBar />
          <div className="flex-grow w-full h-full overflow-scroll">
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
            body <br />
          </div>
        </div>
      </MainLayout>
    </div>
  );
}
